/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package quanlivemaybay;

/**
 *
 * @author FPT
 */
public class BanVeMB extends javax.swing.JInternalFrame {

    /**
     * Creates new form BanVeMB
     */
    public BanVeMB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        btnBanVe = new javax.swing.JButton();
        btnInVe = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMaKhachHang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTenKhachHang = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNgaySinh = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCmnd = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cboGioiTinh = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSoDienThoai = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtDiemDi = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtDiemDen = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtMaVe = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cboMaChuyenBay = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        rdoThuongGia = new javax.swing.JRadioButton();
        rdoPhoThong = new javax.swing.JRadioButton();
        jPanel9 = new javax.swing.JPanel();
        rdoNguoiLon = new javax.swing.JRadioButton();
        rdoTreEm = new javax.swing.JRadioButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtGioBay = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtNgayBay = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtGioiBan = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtNgayBan = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtNoiBan = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtGiaVe = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(900, 568));

        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 5));

        btnBanVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/rsz_ticket-machine.png"))); // NOI18N
        btnBanVe.setText("Bán Vé");
        btnBanVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanVeActionPerformed(evt);
            }
        });
        jPanel11.add(btnBanVe);

        btnInVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/rsz_cash-machine.png"))); // NOI18N
        btnInVe.setText("In vé");
        jPanel11.add(btnInVe);

        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/rsz_exit.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        jPanel11.add(btnThoat);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("Chuong trinh ban ve may bay Poly Ariline");
        jPanel1.add(jLabel1, new java.awt.GridBagConstraints());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thong tin can nhap"));
        jPanel2.setLayout(null);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Thong tin khach hang"));
        jPanel3.setLayout(null);

        jLabel2.setText("Ma khach hang:");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(5, 19, 161, 19);

        txtMaKhachHang.setPreferredSize(new java.awt.Dimension(40, 29));
        jPanel3.add(txtMaKhachHang);
        txtMaKhachHang.setBounds(186, 19, 161, 19);

        jLabel4.setText("Ten khach hang:");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(5, 58, 161, 19);

        txtTenKhachHang.setPreferredSize(new java.awt.Dimension(40, 29));
        jPanel3.add(txtTenKhachHang);
        txtTenKhachHang.setBounds(186, 58, 161, 19);

        jLabel5.setText("Ngay sinh");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(5, 97, 161, 19);

        txtNgaySinh.setPreferredSize(new java.awt.Dimension(40, 29));
        jPanel3.add(txtNgaySinh);
        txtNgaySinh.setBounds(186, 97, 161, 19);

        jLabel6.setText("Cmnd/Ho chieu:");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(5, 136, 161, 19);

        txtCmnd.setPreferredSize(new java.awt.Dimension(40, 29));
        jPanel3.add(txtCmnd);
        txtCmnd.setBounds(186, 136, 161, 19);

        jLabel7.setText("Gioi tinh:");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(5, 175, 161, 19);

        cboGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nu", " " }));
        jPanel3.add(cboGioiTinh);
        cboGioiTinh.setBounds(186, 175, 161, 19);

        jLabel8.setText("Dia chi:");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(5, 214, 161, 19);

        txtDiaChi.setPreferredSize(new java.awt.Dimension(40, 29));
        jPanel3.add(txtDiaChi);
        txtDiaChi.setBounds(186, 214, 161, 19);

        jLabel9.setText("So dien thoai:");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(5, 253, 161, 19);

        txtSoDienThoai.setPreferredSize(new java.awt.Dimension(40, 29));
        jPanel3.add(txtSoDienThoai);
        txtSoDienThoai.setBounds(186, 253, 161, 19);

        jLabel10.setText("Emai[Neu co]:");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(5, 292, 161, 19);

        txtEmail.setPreferredSize(new java.awt.Dimension(40, 29));
        jPanel3.add(txtEmail);
        txtEmail.setBounds(186, 292, 161, 19);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(5, 17, 352, 360);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Thong tin ve va chuyen bay"));

        jPanel5.setLayout(new java.awt.GridLayout(1, 4, 20, 20));

        jLabel13.setText("Diem di:");
        jPanel5.add(jLabel13);
        jPanel5.add(txtDiemDi);

        jLabel12.setText("Diem den:");
        jPanel5.add(jLabel12);
        jPanel5.add(txtDiemDen);

        jPanel6.setLayout(new java.awt.GridLayout(2, 2, 20, 20));

        jLabel3.setText("Ma ve:");
        jPanel6.add(jLabel3);
        jPanel6.add(txtMaVe);

        jLabel11.setText("Ma chuyen bay:");
        jPanel6.add(jLabel11);

        cboMaChuyenBay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PS", "Pk", "PD", "PH" }));
        jPanel6.add(cboMaChuyenBay);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Loai ve"));
        jPanel7.setLayout(new java.awt.GridLayout(1, 2, 20, 20));

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setLayout(new java.awt.GridLayout(1, 2, 20, 16));

        rdoThuongGia.setText("Thuong gia");
        jPanel8.add(rdoThuongGia);

        rdoPhoThong.setText("Pho thong");
        jPanel8.add(rdoPhoThong);

        jPanel7.add(jPanel8);

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setLayout(new java.awt.GridLayout(1, 2, 20, 20));

        rdoNguoiLon.setText("Nguoi lon");
        jPanel9.add(rdoNguoiLon);

        rdoTreEm.setText("Tre em");
        rdoTreEm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoTreEmActionPerformed(evt);
            }
        });
        jPanel9.add(rdoTreEm);

        jPanel7.add(jPanel9);

        jPanel10.setLayout(new java.awt.GridLayout(3, 4, 20, 20));

        jLabel17.setText("Gio bay:");
        jPanel10.add(jLabel17);
        jPanel10.add(txtGioBay);

        jLabel18.setText("Ngay bay:");
        jPanel10.add(jLabel18);
        jPanel10.add(txtNgayBay);

        jLabel14.setText("Gio ban:");
        jPanel10.add(jLabel14);
        jPanel10.add(txtGioiBan);

        jLabel15.setText("Ngay ban:");
        jPanel10.add(jLabel15);
        jPanel10.add(txtNgayBan);

        jLabel16.setText("Noi ban:");
        jPanel10.add(jLabel16);
        jPanel10.add(txtNoiBan);

        jLabel19.setText("Gia ve:");
        jPanel10.add(jLabel19);
        jPanel10.add(txtGiaVe);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4);
        jPanel4.setBounds(357, 17, 500, 360);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 107, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdoTreEmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoTreEmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoTreEmActionPerformed

    private void btnBanVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanVeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBanVeActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        this.hide();
    }//GEN-LAST:event_btnThoatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBanVe;
    private javax.swing.JButton btnInVe;
    private javax.swing.JButton btnThoat;
    private javax.swing.JComboBox<String> cboGioiTinh;
    private javax.swing.JComboBox<String> cboMaChuyenBay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton rdoNguoiLon;
    private javax.swing.JRadioButton rdoPhoThong;
    private javax.swing.JRadioButton rdoThuongGia;
    private javax.swing.JRadioButton rdoTreEm;
    private javax.swing.JTextField txtCmnd;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtDiemDen;
    private javax.swing.JTextField txtDiemDi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGiaVe;
    private javax.swing.JTextField txtGioBay;
    private javax.swing.JTextField txtGioiBan;
    private javax.swing.JTextField txtMaKhachHang;
    private javax.swing.JTextField txtMaVe;
    private javax.swing.JTextField txtNgayBan;
    private javax.swing.JTextField txtNgayBay;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtNoiBan;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTenKhachHang;
    // End of variables declaration//GEN-END:variables
}
