/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package quanlivemaybay;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static quanlivemaybay.helper.InsertData.LoadDataToArray;
import quanlivemaybay.helper.UpdateData;
import quanlivemaybay.model.Controler;
import quanlivemaybay.model.User;

/**
 *
 * @author Administrator
 */
public class infoKhachHang extends javax.swing.JInternalFrame {

    User usTK = new User();
    String tenKhachHang;

    /**
     * Creates new form infoKhachHang
     */
    public infoKhachHang() {
        initComponents();
        Display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMaKH = new javax.swing.JTextField();
        jLabel_TenKhachHang1 = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JTextField();
        jLabel_TenKhachHang2 = new javax.swing.JLabel();
        jLabel_TenKhachHang11 = new javax.swing.JLabel();
        txtRole = new javax.swing.JTextField();
        jLabel_TenKhachHang12 = new javax.swing.JLabel();
        txtMail = new javax.swing.JTextField();
        cboGT = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jLabel_TenKhachHang10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txtSDT = new javax.swing.JTextField();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel_TenKhachHang4 = new javax.swing.JLabel();
        jLabel_TenKhachHang = new javax.swing.JLabel();
        jLabel_TenKhachHang3 = new javax.swing.JLabel();
        jLabel_ThongBao = new javax.swing.JLabel();

        txtMaKH.setEnabled(false);

        jLabel_TenKhachHang1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel_TenKhachHang1.setText("Tên khách hàng");

        jLabel_TenKhachHang2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel_TenKhachHang2.setText("Số điện thoại");

        jLabel_TenKhachHang11.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel_TenKhachHang11.setText("Mật khẩu");

        txtRole.setEnabled(false);

        jLabel_TenKhachHang12.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel_TenKhachHang12.setText("Role");

        cboGT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        cboGT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboGTActionPerformed(evt);
            }
        });

        jButton1.setText("Đổi mật khẩu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnEdit.setText("Cập nhật thông tin");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        jLabel_TenKhachHang10.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel_TenKhachHang10.setText("Tên đăng nhập");

        jButton3.setText("Quay lại");

        txtUser.setEnabled(false);

        txtPass.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("THÔNG TIN CÁ NHÂN");

        jLabel_TenKhachHang4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel_TenKhachHang4.setText("Giới tính");

        jLabel_TenKhachHang.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel_TenKhachHang.setText("Mã khách hàng");

        jLabel_TenKhachHang3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel_TenKhachHang3.setText("Email");

        jLabel_ThongBao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_ThongBao.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_TenKhachHang3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel_ThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(429, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(389, 389, 389)
                                    .addComponent(jLabel1))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel_TenKhachHang)
                                        .addComponent(txtMaKH)
                                        .addComponent(txtTenKH, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                                        .addComponent(txtSDT, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                                        .addComponent(jLabel_TenKhachHang1)
                                        .addComponent(jLabel_TenKhachHang2)
                                        .addComponent(txtMail))
                                    .addGap(55, 55, 55)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel_TenKhachHang4)
                                        .addComponent(jLabel_TenKhachHang10)
                                        .addComponent(txtUser, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                                        .addComponent(jLabel_TenKhachHang11)
                                        .addComponent(txtPass)
                                        .addComponent(jLabel_TenKhachHang12)
                                        .addComponent(txtRole)
                                        .addComponent(cboGT, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 154, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(253, Short.MAX_VALUE)
                .addComponent(jLabel_TenKhachHang3)
                .addGap(41, 41, 41)
                .addComponent(jLabel_ThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel_TenKhachHang)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel_TenKhachHang4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cboGT)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel_TenKhachHang1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel_TenKhachHang10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtUser)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel_TenKhachHang2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel_TenKhachHang11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPass))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel_TenKhachHang12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtRole, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addComponent(txtMail)))
                    .addContainerGap(167, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboGTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboGTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboGTActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        tenKhachHang = txtTenKH.getText();
        if (txtTenKH.getText().isEmpty()) {
            jLabel_ThongBao.setText("*Tên khách hàng chưa được điền");
            return;
        } else {
            jLabel_ThongBao.setText("");
        }
        if (txtSDT.getText().isEmpty()) {
            jLabel_ThongBao.setText("*Số điện thoại chưa được điền");
            return;
        } else {
            jLabel_ThongBao.setText("");
        }
        if (txtMail.getText().isEmpty()) {
            jLabel_ThongBao.setText("*Địa chỉ mail chưa được điền");
            return;
        } else {
            jLabel_ThongBao.setText("");
        }
        if (jLabel_ThongBao.getText().isEmpty()) {
            int luaChon = JOptionPane.showConfirmDialog(this, "Xác nhân sửa thông tin cho khách hàng " + this.tenKhachHang, "Xác nhận sửa", JOptionPane.YES_NO_OPTION);

            if (luaChon == JOptionPane.YES_OPTION) {
                //gọi hàm sửa thông tin
                User userKH = new User(txtMaKH.getText(), txtTenKH.getText(), txtSDT.getText(), cboGT.getSelectedItem().toString(), txtMail.getText(),
                        txtUser.getText(), txtPass.getText(), txtRole.getText());

                try {
                    if (UpdateData.updateTaiKhoan(userKH) == true) {
                        JOptionPane.showMessageDialog(this, "Sửa thành công");
                        LoadDataToArray(txtUser.getText());
                    } else {
                        JOptionPane.showMessageDialog(this, "Sửa không thành công");
                    }
                } catch (Exception ex) {
                    Logger.getLogger(infoKhachHang.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JComboBox<String> cboGT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_TenKhachHang;
    private javax.swing.JLabel jLabel_TenKhachHang1;
    private javax.swing.JLabel jLabel_TenKhachHang10;
    private javax.swing.JLabel jLabel_TenKhachHang11;
    private javax.swing.JLabel jLabel_TenKhachHang12;
    private javax.swing.JLabel jLabel_TenKhachHang2;
    private javax.swing.JLabel jLabel_TenKhachHang3;
    private javax.swing.JLabel jLabel_TenKhachHang4;
    private javax.swing.JLabel jLabel_ThongBao;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtRole;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

    private void Display() {
//        User us = new User();
        for (User us : Controler.arrayListTaiKhoan) {
            if (us.getMaKH().equals(us.getMaKH())) {
                txtMaKH.setText(us.getMaKH());
                txtTenKH.setText(us.getTenKH());
                txtSDT.setText(us.getSDT());
                txtMail.setText(us.getEmail());
                cboGT.setSelectedItem(us.getGioiTinh());
                txtUser.setText(us.getTenDN());
                txtPass.setText(us.getPassword());
                txtRole.setText(us.getRole());
            }
        }
    }

}
